[CM-1357] - Expose updateDefaultSetting method
Kommunicate-io/Kommunicate-React-Native-SDK pull request #42
Opened 2023-04-26 13:33 UTC by amntoppoKM

## What do you want to achieve?
- updateDefaultSetting method is available in Android and iOS, which changes the default setting of a conversation.
- When "Start new Conversation"  is clicked from conversation list screen then these settings are used.
- Exposed a method "updateDefaultSetting" which would update the setting for both Android and iOS.

## How to implement:
- Pass a dynamic setting object to "RNKommunicateChat.updateDefaultSetting" which contains the setting to be passed.

## React Native Javascript code:
```javascript
var setting = {
        "defaultAgentIds": ["amantoppo3199@gmail.com", "amantoppo@kommunicate.io"], //list of agentID
        "defaultBotIds": ["bot-e8xil"], // list of BotID
        "defaultAssignee": "amantoppo3199@gmail.com", 
        "skipRouting": true,
        "teamId": "63641656"
        };
RNKommunicateChat.updateDefaultSetting(setting, (status, message) => {
          console.log(message);
});
```

2023-04-27 06:04 UTC, Sathyan-KM requested changes

2023-04-27 06:04 UTC, Sathyan-KM commented on ios/RNKommunicateChat.swift
> +            }
use if let to check nullability instead of if & check for empty string as well.

2023-04-28 10:09 UTC, mukesh-komm commented on android/src/main/java/io/kommunicate/app/RNKommunicateChatModule.java
> +                        agentList.add(settingMap.getArray("defaultAgentIds").getString(i));
Can't we add all of them in one go instead of loop by converting the array to list?

2023-05-05 12:04 UTC, Sathyan-KM approved these changes

2023-05-09 07:30 UTC, mukesh-komm approved these changes

2023-05-18 05:52 UTC, merged